imports:
    - php
build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
               command: /vendor/bin/phpunit --coverage-clover=my-coverage-file
               coverage:
                   file: my-coverage-file
                   format: php-clover
tools:
    php_changetracking: true
    php_sim: true
    php_pdepend: true
    php_mess_detector: true
    php_analyzer: true
    php_cs_fixer: true
    sensiolabs_security_checker: true