<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'organisation/partial/form/organisation'            => __DIR__ . '//view/organisation/partial/form/organisation.twig',
    'organisation/partial/entity/organisation-info'     => __DIR__ . '//view/organisation/partial/entity/organisation-info.twig',
    'organisation/partial/entity/organisation-title'    => __DIR__ . '//view/organisation/partial/entity/organisation-title.twig',
    'organisation/partial/entity/organisation-metadata' => __DIR__ . '//view/organisation/partial/entity/organisation-metadata.twig',
    'organisation/partial/entity/organisation'          => __DIR__ . '//view/organisation/partial/entity/organisation.twig',
    'organisation/partial/entity/organisation-logo'     => __DIR__ . '//view/organisation/partial/entity/organisation-logo.twig',
    'organisation/partial/list/project'                 => __DIR__ . '//view/organisation/partial/list/project.twig',
    'organisation/partial/list/project_eu'              => __DIR__ . '//view/organisation/partial/list/project_eu.twig',
    'organisation/partial/list/article'                 => __DIR__ . '//view/organisation/partial/list/article.twig',
    'organisation/partial/list/organisation'            => __DIR__ . '//view/organisation/partial/list/organisation.twig',
    'organisation/partial/list/organisation-search'     => __DIR__ . '//view/organisation/partial/list/organisation-search.twig',
    'organisation/partial/pagination-control'           => __DIR__ . '//view/organisation/partial/pagination-control.twig',
);
