<?php
/**
 * ITEA Office all rights reserved
 *
 * PHP Version 7
 *
 * @category    Project
 *
 * @author      Johan van der Heide <johan.van.der.heide@itea3.org>
 * @copyright   Copyright (c) 2004-2017 ITEA Office (https://itea3.org)
 * @license     https://itea3.org/license.txt proprietary
 *
 * @link        http://github.com/iteaoffice/project for the canonical source repository
 */

namespace Organisation\Form;

use Doctrine\ORM\EntityManager;
use DoctrineModule\Stdlib\Hydrator\DoctrineObject as DoctrineHydrator;
use DoctrineORMModule\Form\Element\EntityMultiCheckbox;
use DoctrineORMModule\Form\Element\EntityRadio;
use DoctrineORMModule\Form\Element\EntitySelect;
use Organisation\Entity;
use Zend\Form\Annotation\AnnotationBuilder;
use Zend\Form\Element;
use Zend\Form\Element\Radio;
use Zend\Form\Fieldset;
use Zend\Form\Form;

/**
 * Class ObjectFieldset
 *
 * @package Organisation\Form
 */
final class ObjectFieldset extends Fieldset
{
    /**
     * @var EntityManager
     */
    private $entityManager;

    /**
     * @param EntityManager         $entityManager
     * @param Entity\EntityAbstract $object
     *
     * @todo Directly use the form generated by $builder->createForm()
     */
    public function __construct(EntityManager $entityManager, Entity\AbstractEntity $object)
    {
        parent::__construct($object->get('underscore_entity_name'));
        $this->entityManager = $entityManager;
        $doctrineHydrator    = new DoctrineHydrator($entityManager);
        $this->setHydrator($doctrineHydrator)->setObject($object);
        $builder = new AnnotationBuilder();

        // createForm() already creates a proper form, so attaching its elements
        // to $this is only for backward compatibility
        $data = $builder->createForm($object);
        $this->addElements($data, $object, $this);
    }

    /**
     * Recursively add form elements and sub-fieldsets
     *
     * @param Fieldset|Form         $dataFieldset
     * @param Entity\EntityAbstract $object
     * @param Fieldset              $baseFieldset
     */
    protected function addElements(Fieldset $dataFieldset, Entity\AbstractEntity $object, Fieldset $baseFieldset = null)
    {
        /** @var Element $element */
        foreach ($dataFieldset->getElements() as $element) {
            $this->parseElement($element, $object);
            // Add only when a type is provided
            if (! array_key_exists('type', $element->getAttributes())) {
                continue;
            }

            if ($baseFieldset instanceof Fieldset) {
                $baseFieldset->add($element);
            } else {
                $dataFieldset->add($element);
            }
        }

        // Add sub-fieldsets
        foreach ($dataFieldset->getFieldsets() as $subFieldset) {
            /** @var Fieldset $subFieldset */
            $subFieldset->setHydrator($this->getHydrator());
            $subFieldset->setAllowedObjectBindingClass(get_class($subFieldset->getObject()));
            $this->addElements($subFieldset, $subFieldset->getObject());
            $this->add($subFieldset);
        }
    }

    /**
     * @param Element               $element
     * @param Entity\EntityAbstract $object
     */
    protected function parseElement(Element $element, Entity\AbstractEntity $object)
    {
        // Go over each element to add the objectManager to the EntitySelect
        /** Element $element */
        if ($element instanceof EntitySelect
            || $element instanceof EntityMultiCheckbox
            || $element instanceof EntityRadio
        ) {
            $element->setOptions(
                array_merge($element->getOptions(), ['object_manager' => $this->entityManager])
            );
        }
        if (($element instanceof Radio) && !($element instanceof EntityRadio)) {
            $attributes        = $element->getAttributes();
            $valueOptionsArray = sprintf('get%s', ucfirst($attributes['array']));

            $element->setOptions(
                array_merge($element->getOptions(), ['value_options' => $object::$valueOptionsArray()])
            );
        }
    }
}
